name: htmltopdfwidgets
description: Htmlt to pdf widgets library convert html text to pdf widgets
version: 1.0.3
homepage: https://github.com/alihassan143/htmltopdfwidgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pdf:
  html:
  http:
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      path: pdf/
      ref: master
dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.1.1
  test: ">=1.16.0 <2.0.0"
